djforum/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    HomePageView
)


admin.site.site_title = 'DJ Forum'
admin.site.site_header = 'DJ Forum'
admin.site.index_title = 'DJ Forum Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', HomePageView.as_view(), name='home'),
    path('', include('forums.urls', namespace='forums')),    
]

forums/urls.py
from django.urls import path
from .views import (
    QuestionListView,
    QuestionDetailsView,
    TopicListview,
    TopicCreateView,
    TopicDeleteView
)

app_name = 'forums'
urlpatterns = [
    path('', TopicListview.as_view(), name='topic-list'),
    path('topic/<slug:topic>/', QuestionListView.as_view(), name='question-list'),
    path('topic/<slug:topic>/question/<slug:slug>/', QuestionDetailsView.as_view(), name='question-slug'),
    path('topic-create/', TopicCreateView.as_view(), name='topic-create'),
    path('topic-delete/<int:pk>', TopicDeleteView.as_view(), name='topic-delete')
]

forums/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Topic(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']


class Question(models.Model):
    STATUS_CHOICES = (
        ('success', 'Active'),
        ('info', 'Suspended'),
        ('red', 'Spam'),
        ('primary', 'Solved')
    )
    title = models.CharField(max_length=400)
    description = models.TextField()
    slug = models.SlugField(max_length=250)
    tags = models.CharField(max_length=500)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=250, choices=STATUS_CHOICES)
    views = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']


class Answer(models.Model):
    answer = models.CharField(max_length=500)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.answer

    class Meta:
        ordering = ['-created']

forums/forms.py
from django import forms
from .models import Topic, Question, Answer


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'
        # exclude = ['user']

djforum/views.py
from django.views import generic
from forums.models import Question, Topic


class HomePageView(generic.ListView):
    template_name = 'pages/home.html'
    queryset = Question.objects.all()
    context_object_name = 'questions'

forums/views.py
from django.shortcuts import render, reverse
from .models import Question, Topic
from django.views import generic
from .forms import TopicForm


class QuestionListView(generic.ListView):
    template_name = 'forum/question-list.html'
    # queryset = Question.objects.all()
    context_object_name = 'questions'

    def get_queryset(self):
        queryset = Question.objects.filter(topic__slug=self.kwargs['topic'])
        return queryset


class QuestionDetailsView(generic.DetailView):
    template_name = 'forum/question-details.html'
    slug_field = 'slug'
    queryset = Question.objects.all()
    context_object_name = 'question'


class TopicListview(generic.ListView):
    template_name = 'forum/topic-list.html'
    queryset = Topic.objects.all()
    context_object_name = 'topics'


class TopicCreateView(generic.CreateView):
    template_name = 'forum/topic-create.html'
    queryset = Topic.objects.all()
    form_class = TopicForm

    def get_success_url(self):
        return reverse('forums:topic-list')

    def form_valid(self, form):
        return super().form_valid(form)


class TopicDeleteView(generic.DeleteView):
    template_name = 'forum/topic-delete.html'
    queryset = Topic.objects.all()
    context_object_name = 'topic'

    def get_success_url(self):
        return reverse('forums:topic-list')

templates/forum/question-details.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <h2>{{ question.topic }}</h2>
                </div>
                                <div class="col-lg-7 col-md-7 col-sm-12">
                                    <ul class="breadcrumb float-md-right padding-0">
                                        <li class="breadcrumb-item"><a href="{% url 'forums:question-list' %}"><i class="zmdi zmdi-home"></i></a></li>
                                        <li class="breadcrumb-item"><a href="{% url 'forums:question-list' %}">Questions</a></li>
                                        <li class="breadcrumb-item active">Question</li>
                                    </ul>
                                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="body project_report">
                        <h1>{{ question.title }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/forum/question-list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                {#                <div class="col-lg-5 col-md-5 col-sm-12">#}
                {#                    <h2>Latest Forum Questions</h2>#}
                {#                </div>#}
                {#                <div class="col-lg-7 col-md-7 col-sm-12">#}
                {#                    <ul class="breadcrumb float-md-right padding-0">#}
                {#                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>#}
                {#                        <li class="breadcrumb-item"><a href="javascript:void(0);">Pages</a></li>#}
                {#                        <li class="breadcrumb-item active">Projects List</li>#}
                {#                    </ul>#}
                {#                </div>#}
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="body project_report">
                        <div class="table-responsive">
                            <table class="table m-b-0 table-hover">
                                <thead>
                                <tr>
                                    <th>Status</th>
                                    <th>Question</th>
                                    <th>Topic</th>
                                    <th>Owner</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for question in questions %}
                                    <tr>
                                        <td>
                                            <span class="badge badge-{{ question.status }}">{{ question.get_status_display }}</span>
                                        </td>
                                        <td class="project-title">
                                            <h6><a href="#">{{ question.title }}</a></h6>
                                            <small>Created {{ question.created | date }}</small>
                                        </td>
                                        <td>
                                            {{ question.topic }}
                                        </td>
                                        <td>
                                            {{ question.user }}
                                        </td>
                                        <td class="project-actions">
                                            <a href="{% url 'forums:question-slug' question.slug %}" class="btn btn-neutral btn-sm"><i class="zmdi zmdi-eye"></i></a>
                                            <a href="#" class="btn btn-neutral btn-sm"><i
                                                    class="zmdi zmdi-edit"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/forum/topic-create.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                                <div class="col-lg-5 col-md-5 col-sm-12">
{#                                    <h2>Latest Forum Questions</h2>#}
                                </div>
                                <div class="col-lg-7 col-md-7 col-sm-12">
                                    <a href="{% url 'forums:topic-list' %}" class="btn btn-sm btn-warning float-right"><i class="fc-icon fc-icon-left-double-arrow"></i>Go Back</a>
{#                                    <ul class="breadcrumb float-md-right padding-0">#}
{#                                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>#}
{#                                        <li class="breadcrumb-item"><a href="javascript:void(0);">Pages</a></li>#}
{#                                        <li class="breadcrumb-item active">Projects List</li>#}
{#                                    </ul>#}
                                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="body project_report">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">CREATE</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/forum/topic-delete.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                                <div class="col-lg-5 col-md-5 col-sm-12">
{#                                    <h2>Latest Forum Questions</h2>#}
                                </div>
                                <div class="col-lg-7 col-md-7 col-sm-12">
                                    <a href="{% url 'forums:topic-list' %}" class="btn btn-sm btn-warning float-right"><i class="fc-icon fc-icon-left-double-arrow"></i>Go Back</a>
{#                                    <ul class="breadcrumb float-md-right padding-0">#}
{#                                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>#}
{#                                        <li class="breadcrumb-item"><a href="javascript:void(0);">Pages</a></li>#}
{#                                        <li class="breadcrumb-item active">Projects List</li>#}
{#                                    </ul>#}
                                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="body project_report">
                        <h5>Are you sure you want to delete <em>{{ topic.title }}</em>?</h5>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-danger">DELETE</button>
                            <a class="btn btn-success" href="{% url 'forums:topic-list' %}">Nah, go back!</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/forum/topic-list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                                <div class="col-lg-5 col-md-5 col-sm-12">
{#                                    <h2>Latest Forum Questions</h2>#}
                                </div>
                                <div class="col-lg-7 col-md-7 col-sm-12">
                                    <a href="{% url 'forums:topic-create' %}" class="btn btn-sm btn-neutral float-right">Create New Topic</a>
{#                                    <ul class="breadcrumb float-md-right padding-0">#}
{#                                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>#}
{#                                        <li class="breadcrumb-item"><a href="javascript:void(0);">Pages</a></li>#}
{#                                        <li class="breadcrumb-item active">Projects List</li>#}
{#                                    </ul>#}
                                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="body project_report">
                        <div class="table-responsive">
                            <table class="table m-b-0 table-hover">
                                <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>User</th>
                                    <th>Questions</th>
                                    {#                                    <th>Created</th>#}
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for topic in topics %}
                                    <tr>
                                        <td>
                                            <span>{{ topic.title }}</span>
                                        </td>
                                        <td class="project-title">
                                            <h6><a href="#">{{ topic.user }}</a></h6>
                                            <small>Created {{ topic.created | date }}</small>
                                        </td>
                                        <td>
                                            <span class="badge badge-{% if topic.question_set.all %}success{% else %}danger{% endif %}">{{ topic.question_set.all | length }} Questions</span>
                                        </td>
                                        {#                                        <td>#}
                                        {#                                            {{ question.user }}#}
                                        {#                                        </td>#}
                                        <td class="project-actions">
                                            <a href="{% url 'forums:question-list' topic.slug %}"
                                               class="btn btn-neutral btn-sm"><i class="zmdi zmdi-eye"></i></a>
                                            <a href="{% url 'forums:topic-delete' topic.id %}" class="btn btn-neutral btn-sm"><i
                                                    class="zmdi zmdi-delete"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}
{% block main %}
    <div class="block-header">
        <div class="row clearfix">
            <div class="col-lg-5 col-md-5 col-sm-12">
                <h2>Stater Page</h2>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-12">
                <ul class="breadcrumb float-md-right padding-0">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Pages</a></li>
                    <li class="breadcrumb-item active">Stater Page</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Blank</strong> Page</h2>
                    <ul class="header-dropdown">
                        <li class="dropdown"><a href="javascript:void(0);" class="dropdown-toggle"
                                                data-toggle="dropdown" role="button" aria-haspopup="true"
                                                aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else</a></li>
                                <li><a href="javascript:void(0);" class="boxs-close">Delete</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <h4 class="margin-0">Stater page</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}